# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    working_directory: ~/muzykant-frontend
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: muzykant-frontend-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm audit fix
      - save_cache:
          key: muzykant-frontend-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
